add: feature/se-57/fix
SE2-WS23/Skillverse-Web pull request #26
Opened 2023-11-22 17:32 UTC by 11Meru11

closes SE2-WE23/documentation#57

Page to set the neccessary skills for the job

2023-11-22 18:00 UTC, Arkcorner requested changes

2023-11-22 18:00 UTC, Arkcorner commented on src/routes.jsx
> +    element: <JobDescriptionPage />,
```suggestion
  {
    path: "job-description",
    element: <JobDescriptionPage />,
```
Job description is doubled in route

2023-11-22 18:00 UTC, Arkcorner commented on src/routes.jsx
please add the import for your page at the top

2023-11-22 18:00 UTC, Arkcorner commented on src/pages/JobDescription/JobDescriptionPage.jsx
> +      </Grid>
Please adjust spacing to be more like the figma (same distance in between the items at the sides and top/bottom)

2023-11-22 18:00 UTC, Arkcorner commented on src/pages/JobDescription/JobDescriptionPage.jsx
> +      <h2>Select relevant Skills for the job</h2>
please add positioning so that its not completely stuck in the top left corner

2023-11-23 08:07 UTC, julix14 commented
Wrong branch naming.

2023-11-23 08:07 UTC, closed without merging