Feature/se 46
SE2-WS23/Skillverse-Web pull request #36
Opened 2023-11-30 12:54 UTC by Arkcorner

closes SE2-WS23/documentation#46

2023-12-03 20:32 UTC, Chrissydrx requested changes

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
Layout is broken for small devices. Avatar is stretched.
![image](https://github.com/SE2-WS23/Skillverse-Web/assets/37250473/36bed9c0-b996-4a20-9727-4f2b0fbbff03)

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
You don't use our prettier settings

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +  }
Please add space between those functions

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +              <Avatar sx={{ width: "10vw", height: "20vh", variant: "circular" }} />
Weird width and height settings for avatar

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +  const [selectedFiles, setSelectedFiles] = useState([]);
That state can not be accessed in your page component

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +  };
This seems like you can upload multiple files at once, but you can only chose one file in the picker

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +        <Box key={file.name} display="flex" alignItems="center" mb={1}>
Use as key an uuid

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/components/UploadedFile.jsx
> +      <Typography variant="subtitle1">Selected File: {fileName}</Typography>
Set default for filename

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/components/UploadedFile.jsx
> +    onDelete(fileName);
Set default

2023-12-03 20:32 UTC, Chrissydrx commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +  };
Does this click the upload-file input field?

2023-12-06 17:38 UTC, Arkcorner commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
The Layout for small devices has been fixed

2023-12-06 17:38 UTC, Arkcorner commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
I now use the Prettier settings

2023-12-06 17:49 UTC, Arkcorner commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +  }
theres now spaces between the functions

2023-12-06 17:51 UTC, Arkcorner commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +              <Avatar sx={{ width: "10vw", height: "20vh", variant: "circular" }} />
the sizes are now both dependent on the width of the screen and i didnt really see a convention from us for this so i tried to make it just look good

2023-12-06 17:51 UTC, Arkcorner commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +        <Box key={file.name} display="flex" alignItems="center" mb={1}>
did

2023-12-11 20:41 UTC, Chrissydrx requested changes

2023-12-11 20:41 UTC, Chrissydrx commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
![image](https://github.com/SE2-WS23/Skillverse-Web/assets/37250473/4a2b9222-1d03-43a1-ae2c-0526caff5630)
Still not completely fixed for width 900px

2023-12-11 20:41 UTC, Chrissydrx commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +  const [selectedFiles, setSelectedFiles] = useState([]);
Still not fixed

2023-12-11 20:41 UTC, Chrissydrx commented on src/pages/EmployeeCreation/components/UploadedFile.jsx
> +    onDelete(fileName);
or at least a fallback

2023-12-12 16:47 UTC, Arkcorner commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
fixed

2023-12-12 16:54 UTC, Arkcorner commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +  };
Yes files need to be uploaded one at a time array is just to allow multiple uploads one after the other

2023-12-12 16:54 UTC, Arkcorner commented on src/pages/EmployeeCreation/components/UploadedFile.jsx
> +    onDelete(fileName);
default should be set

2023-12-12 16:55 UTC, Arkcorner commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +  };
yes a straight up on click doesnt seem to work and i got this from coPilot

2023-12-12 17:41 UTC, Arkcorner commented on src/pages/EmployeeCreation/components/UploadedFile.jsx
> +      <Typography variant="subtitle1">Selected File: {fileName}</Typography>
did

2023-12-13 16:27 UTC, Arkcorner commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
<img width="428" alt="Screenshot 2023-12-13 at 17 24 38" src="https://github.com/SE2-WS23/Skillverse-Web/assets/115979577/e1b19147-99f0-402a-ada0-86c2e610eb1a">

2023-12-14 08:29 UTC, Arkcorner commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +  const [selectedFiles, setSelectedFiles] = useState([]);
fixed

2024-01-13 18:17 UTC, j0world commented
If you open Employee overview on a smaller screen you can see that it doesn't open at the top. Others don't do that either but if you want to fix it you can ask Uzoma on how to do that. 
Only being able to upload a single file at a time is already mentioned by Christian.
I can create a new employee without any information which isn't as bad because there's no logic behind the handleSubmit() anyway but if you're ambitious, that shouldn't be too difficult to change.

2024-01-13 18:19 UTC, j0world commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +                position='absolute'
The profile picture scales but the plus button doesn't.

2024-01-13 18:27 UTC, j0world requested changes
If I add too much stuff, either in Files or Extra info, the Create Employee button lingers at the bottom and can't be moved away.
The same for the profile picture but with the top.

2024-01-13 18:31 UTC, j0world commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +                label='Phone number'
Please change to "Phone Number" according to title case

2024-01-13 18:32 UTC, j0world commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +                label='Extra info'
Please change to "Extra Info" according title case

2024-01-16 17:45 UTC, j0world commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +                position='absolute'
width changes now, height doesn't seem to scale correctly

2024-01-17 08:06 UTC, Arkcorner commented on src/pages/EmployeeCreation/EmployeeCreationPage.jsx
> +                position='absolute'
the + in the fab hinders it from scaling correctly for all sizes but in my testing it was ok for the 900 by 900 px and full screen size I'm not sure how to make it completely dynamic

2024-01-17 13:37 UTC, j0world approved these changes

2024-01-17 13:47 UTC, j0world requested changes

2024-01-17 13:47 UTC, j0world commented on src/pages/EmployeeCreation/components/UploadBox.jsx
I clicked random things out of curiosity, please make it possible to upload multiple files and I shall also willingly approve

2024-01-23 15:48 UTC, Arkcorner commented on src/pages/EmployeeCreation/components/UploadBox.jsx
> +  };
Fixed the Input component of material UI mad this way harder as it didn´t have the multiple property defined so i switched to a normal input field to more suit the needs of our website as its hidden anyway

2024-01-23 15:49 UTC, Arkcorner commented on src/pages/EmployeeCreation/components/UploadBox.jsx
did

2024-01-23 17:50 UTC, j0world commented on src/pages/EmployeeCreation/components/UploadBox.jsx
indeed works now. 
If I upload a document with too long of a title however, it messes with your padding
<img width="514" alt="Screenshot 2024-01-23 at 18 47 44" src="https://github.com/SE2-WS23/Skillverse-Web/assets/136974808/c6f47e24-6fdd-4474-92c9-87c92e4eb738">

2024-01-23 18:40 UTC, j0world approved these changes

2024-01-24 01:32 UTC, Chrissydrx approved these changes
I trust that you guys did a good job. I didn't check the PR, but because I don't have time in the next days, I will approve this, so that I don't block the team

2024-01-24 10:19 UTC, merged